
%%%-------------------------------------------------------------------
%%% @author adrianx 
%%% @email  adrianx.lau@gmail.com adrianx@163.com
%%% @copyright (C) 2021, Amaze Game framwork
%%% @doc
%%%
%%% @end
%%% Created : 2021.10.12 
%%%-------------------------------------------------------------------
%%%

-define(AGB_TIMEZONE_INDEX, #{"NDT" => ["America/St_Johns","Canada/Newfoundland"],
  "CHOT" => ["Asia/Choibalsan"],
  "WEST" =>
      ["Africa/Casablanca","Africa/El_Aaiun","Atlantic/Canary",
       "Atlantic/Faeroe","Atlantic/Faroe","Atlantic/Madeira",
       "Europe/Lisbon","Portugal","WET"],
  "GMT+6" => ["Etc/GMT+6"],
  "FJST" => ["Pacific/Fiji"],
  "GMT-2" => ["Etc/GMT-2"],
  "ULAT" => ["Asia/Ulaanbaatar","Asia/Ulan_Bator"],
  "MHT" => ["Kwajalein","Pacific/Kwajalein","Pacific/Majuro"],
  "SYOT" => ["Antarctica/Syowa"],
  "CLST" =>
      ["America/Santiago","Antarctica/Palmer","Chile/Continental"],
  "BNT" => ["Asia/Brunei"],
  "GMT+11" => ["Etc/GMT+11"],
  "ART" =>
      ["America/Argentina/Buenos_Aires",
       "America/Argentina/Catamarca",
       "America/Argentina/ComodRivadavia",
       "America/Argentina/Cordoba","America/Argentina/Jujuy",
       "America/Argentina/La_Rioja","America/Argentina/Mendoza",
       "America/Argentina/Rio_Gallegos","America/Argentina/Salta",
       "America/Argentina/San_Juan","America/Argentina/San_Luis",
       "America/Argentina/Tucuman","America/Argentina/Ushuaia",
       "America/Buenos_Aires","America/Catamarca",
       "America/Cordoba","America/Jujuy","America/Mendoza",
       "America/Rosario"],
  "WGST" => ["America/Godthab"],
  "VOLT" => ["Europe/Volgograd"],
  "AFT" => ["Asia/Kabul"],
  "QYZT" => ["Asia/Qyzylorda"],
  "NST" => ["America/St_Johns","Canada/Newfoundland"],
  "GMT+5" => ["Etc/GMT+5"],
  "COT" => ["America/Bogota"],
  "RET" => ["Indian/Reunion"],
  "GMT-1" => ["Etc/GMT-1"],
  "GMT-7" => ["Etc/GMT-7"],
  "VOST" => ["Antarctica/Vostok"],
  "MDT" =>
      ["America/Boise","America/Cambridge_Bay",
       "America/Chihuahua","America/Denver","America/Edmonton",
       "America/Inuvik","America/Mazatlan","America/Ojinaga",
       "America/Shiprock","America/Yellowknife","Canada/Mountain",
       "MST7MDT","Mexico/BajaSur","Navajo","US/Mountain"],
  "WET" =>
      ["Africa/Casablanca","Africa/El_Aaiun","Atlantic/Canary",
       "Atlantic/Faeroe","Atlantic/Faroe","Atlantic/Madeira",
       "Europe/Lisbon","Portugal","WET"],
  "ChST" => ["Pacific/Guam","Pacific/Saipan"],
  "FNT" => ["America/Noronha","Brazil/DeNoronha"],
  "NPT" => ["Asia/Kathmandu","Asia/Katmandu"],
  "CCT" => ["Indian/Cocos"],
  "EDT" =>
      ["America/Detroit","America/Fort_Wayne",
       "America/Grand_Turk","America/Indiana/Indianapolis",
       "America/Indiana/Marengo","America/Indiana/Petersburg",
       "America/Indiana/Vevay","America/Indiana/Vincennes",
       "America/Indiana/Winamac","America/Indianapolis",
       "America/Iqaluit","America/Kentucky/Louisville",
       "America/Kentucky/Monticello","America/Louisville",
       "America/Montreal","America/Nassau","America/New_York",
       "America/Nipigon","America/Pangnirtung",
       "America/Port-au-Prince","America/Thunder_Bay",
       "America/Toronto","Canada/Eastern","EST5EDT",
       "US/East-Indiana","US/Eastern","US/Michigan"],
  "CKT" => ["Pacific/Rarotonga"],
  "GMT+9" => ["Etc/GMT+9"],
  "VLAT" => ["Asia/Ust-Nera","Asia/Vladivostok"],
  "EAST" => ["Chile/EasterIsland","Pacific/Easter"],
  "ALMT" => ["Asia/Almaty"],
  "CHADT" => ["NZ-CHAT","Pacific/Chatham"],
  "WAT" =>
      ["Africa/Bangui","Africa/Brazzaville","Africa/Douala",
       "Africa/Kinshasa","Africa/Lagos","Africa/Libreville",
       "Africa/Luanda","Africa/Malabo","Africa/Ndjamena",
       "Africa/Niamey","Africa/Porto-Novo","Africa/Windhoek"],
  "AZST" => ["Asia/Baku"],
  "GST" =>
      ["Asia/Dubai","Asia/Muscat","Atlantic/South_Georgia"],
  "GMT+3" => ["Etc/GMT+3"],
  "MEST" => ["MET"],
  "AZOT" => ["Atlantic/Azores"],
  "MAWT" => ["Antarctica/Mawson"],
  "BOT" => ["America/La_Paz"],
  "PHT" => ["Asia/Manila"],
  "IRKT" => ["Asia/Irkutsk"],
  "UCT" => ["Etc/UCT","UCT"],
  "CHAST" => ["NZ-CHAT","Pacific/Chatham"],
  "VET" => ["America/Caracas"],
  "PDT" =>
      ["America/Dawson","America/Ensenada","America/Los_Angeles",
       "America/Santa_Isabel","America/Tijuana",
       "America/Vancouver","America/Whitehorse","Canada/Pacific",
       "Canada/Yukon","Mexico/BajaNorte","PST8PDT","US/Pacific"],
  "KRAT" => ["Asia/Krasnoyarsk"],
  "GMT+2" => ["Etc/GMT+2"],
  "OMST" => ["Asia/Omsk"],
  "PET" => ["America/Lima"],
  "ORAT" => ["Asia/Oral"],
  "NOVT" => ["Asia/Novokuznetsk","Asia/Novosibirsk"],
  "FET" => ["Europe/Kaliningrad","Europe/Minsk"],
  "CLT" =>
      ["America/Santiago","Antarctica/Palmer","Chile/Continental"],
  "TKT" => ["Pacific/Fakaofo"],
  "AZOST" => ["Atlantic/Azores"],
  "EST" =>
      ["America/Atikokan","America/Cayman",
       "America/Coral_Harbour","America/Detroit",
       "America/Fort_Wayne","America/Grand_Turk",
       "America/Indiana/Indianapolis","America/Indiana/Marengo",
       "America/Indiana/Petersburg","America/Indiana/Vevay",
       "America/Indiana/Vincennes","America/Indiana/Winamac",
       "America/Indianapolis","America/Iqaluit","America/Jamaica",
       "America/Kentucky/Louisville","America/Kentucky/Monticello",
       "America/Louisville","America/Montreal","America/Nassau",
       "America/New_York","America/Nipigon","America/Panama",
       "America/Pangnirtung","America/Port-au-Prince",
       "America/Thunder_Bay","America/Toronto","Australia/ACT",
       "Australia/ACT","Australia/Brisbane","Australia/Canberra",
       "Australia/Canberra","Australia/Currie","Australia/Currie",
       "Australia/Hobart","Australia/Hobart","Australia/Lindeman",
       "Australia/Melbourne","Australia/Melbourne","Australia/NSW",
       "Australia/NSW","Australia/Queensland","Australia/Sydney",
       "Australia/Sydney","Australia/Tasmania",
       "Australia/Tasmania","Australia/Victoria",
       "Australia/Victoria","Canada/Eastern","EST","EST5EDT",
       "Jamaica","US/East-Indiana","US/Eastern","US/Michigan"],
  "NRT" => ["Pacific/Nauru"],
  "PONT" => ["Pacific/Pohnpei","Pacific/Ponape"],
  "PST" =>
      ["America/Dawson","America/Ensenada","America/Los_Angeles",
       "America/Santa_Isabel","America/Tijuana",
       "America/Vancouver","America/Whitehorse","Canada/Pacific",
       "Canada/Yukon","Mexico/BajaNorte","PST8PDT",
       "Pacific/Pitcairn","US/Pacific"],
  "NUT" => ["Pacific/Niue"],
  "HKT" => ["Asia/Hong_Kong","Hongkong"],
  "SGT" => ["Asia/Singapore","Singapore"],
  "NFT" => ["Pacific/Norfolk"],
  "WIB" => ["Asia/Jakarta","Asia/Pontianak"],
  "WAKT" => ["Pacific/Wake"],
  "IOT" => ["Indian/Chagos"],
  "GMT-10" => ["Etc/GMT-10"],
  "GFT" => ["America/Cayenne"],
  "KOST" => ["Pacific/Kosrae"],
  "ROTT" => ["Antarctica/Rothera"],
  "GAMT" => ["Pacific/Gambier"],
  "BDT" => ["Asia/Dacca","Asia/Dhaka"],
  "WAST" => ["Africa/Windhoek"],
  "LINT" => ["Pacific/Kiritimati"],
  "AKST" =>
      ["America/Anchorage","America/Juneau","America/Nome",
       "America/Sitka","America/Yakutat","US/Alaska"],
  "GMT-9" => ["Etc/GMT-9"],
  "MYT" => ["Asia/Kuala_Lumpur","Asia/Kuching"],
  "WIT" => ["Asia/Jayapura"],
  "UTC" =>
      ["Etc/UTC","Etc/Universal","Etc/Zulu","UTC","Universal",
       "Zulu"],
  "GMT-6" => ["Etc/GMT-6"],
  "PWT" => ["Pacific/Palau"],
  "EET" =>
      ["Africa/Cairo","Africa/Tripoli","Asia/Amman","Asia/Beirut",
       "Asia/Damascus","Asia/Gaza","Asia/Hebron","Asia/Istanbul",
       "Asia/Nicosia","EET","Egypt","Europe/Athens",
       "Europe/Bucharest","Europe/Chisinau","Europe/Helsinki",
       "Europe/Istanbul","Europe/Kiev","Europe/Mariehamn",
       "Europe/Nicosia","Europe/Riga","Europe/Simferopol",
       "Europe/Sofia","Europe/Tallinn","Europe/Tiraspol",
       "Europe/Uzhgorod","Europe/Vilnius","Europe/Zaporozhye",
       "Libya","Turkey"],
  "CWST" => ["Australia/Eucla"],
  "TLT" => ["Asia/Dili"],
  "YAKT" => ["Asia/Khandyga","Asia/Yakutsk"],
  "WSDT" => ["Pacific/Apia"],
  "PYT" => ["America/Asuncion"],
  "FJT" => ["Pacific/Fiji"],
  "WFT" => ["Pacific/Wallis"],
  "BST" =>
      ["Europe/Belfast","Europe/Guernsey","Europe/Isle_of_Man",
       "Europe/Jersey","Europe/London","GB","GB-Eire"],
  "SAMT" => ["Europe/Samara"],
  "MART" => ["Pacific/Marquesas"],
  "TMT" => ["Asia/Ashgabat","Asia/Ashkhabad"],
  "HST" =>
      ["HST","Pacific/Honolulu","Pacific/Johnston","US/Hawaii"],
  "AMT" =>
      ["America/Boa_Vista","America/Campo_Grande",
       "America/Cuiaba","America/Manaus","America/Porto_Velho",
       "Asia/Yerevan","Brazil/West"],
  "AQTT" => ["Asia/Aqtau","Asia/Aqtobe"],
  "GMT-8" => ["Etc/GMT-8"],
  "SST" =>
      ["Pacific/Midway","Pacific/Pago_Pago","Pacific/Samoa",
       "US/Samoa"],
  "EASST" => ["Chile/EasterIsland","Pacific/Easter"],
  "GMT+4" => ["Etc/GMT+4"],
  "GMT-11" => ["Etc/GMT-11"],
  "AST" =>
      ["America/Anguilla","America/Antigua","America/Aruba",
       "America/Barbados","America/Blanc-Sablon","America/Curacao",
       "America/Dominica","America/Glace_Bay","America/Goose_Bay",
       "America/Grenada","America/Guadeloupe","America/Halifax",
       "America/Kralendijk","America/Lower_Princes",
       "America/Marigot","America/Martinique","America/Moncton",
       "America/Montserrat","America/Port_of_Spain",
       "America/Puerto_Rico","America/Santo_Domingo",
       "America/St_Barthelemy","America/St_Kitts",
       "America/St_Lucia","America/St_Thomas","America/St_Vincent",
       "America/Thule","America/Tortola","America/Virgin",
       "Asia/Aden","Asia/Baghdad","Asia/Bahrain","Asia/Kuwait",
       "Asia/Qatar","Asia/Riyadh","Atlantic/Bermuda",
       "Canada/Atlantic"],
  "AZT" => ["Asia/Baku"],
  "PMDT" => ["America/Miquelon"],
  "SBT" => ["Pacific/Guadalcanal"],
  "MVT" => ["Indian/Maldives"],
  "UYT" => ["America/Montevideo"],
  "GET" => ["Asia/Tbilisi"],
  "EGT" => ["America/Scoresbysund"],
  "EAT" =>
      ["Africa/Addis_Ababa","Africa/Asmara","Africa/Asmera",
       "Africa/Dar_es_Salaam","Africa/Djibouti","Africa/Juba",
       "Africa/Kampala","Africa/Khartoum","Africa/Mogadishu",
       "Africa/Nairobi","Indian/Antananarivo","Indian/Comoro",
       "Indian/Mayotte"],
  "VUT" => ["Pacific/Efate"],
  "DDUT" => ["Antarctica/DumontDUrville"],
  "MeST" => ["America/Metlakatla"],
  "CXT" => ["Indian/Christmas"],
  "GILT" => ["Pacific/Tarawa"],
  "GMT+1" => ["Etc/GMT+1"],
  "IDT" => ["Asia/Jerusalem","Asia/Tel_Aviv","Israel"],
  "IRDT" => ["Asia/Tehran","Iran"],
  "MSK" => ["Europe/Moscow","W-SU"],
  "SCT" => ["Indian/Mahe"],
  "MET" => ["MET"],
  "MMT" => ["Asia/Rangoon"],
  "EEST" =>
      ["Asia/Amman","Asia/Beirut","Asia/Damascus","Asia/Gaza",
       "Asia/Hebron","Asia/Istanbul","Asia/Nicosia","EET",
       "Europe/Athens","Europe/Bucharest","Europe/Chisinau",
       "Europe/Helsinki","Europe/Istanbul","Europe/Kiev",
       "Europe/Mariehamn","Europe/Nicosia","Europe/Riga",
       "Europe/Simferopol","Europe/Sofia","Europe/Tallinn",
       "Europe/Tiraspol","Europe/Uzhgorod","Europe/Vilnius",
       "Europe/Zaporozhye","Turkey"],
  "NZDT" =>
      ["Antarctica/McMurdo","Antarctica/South_Pole","NZ",
       "Pacific/Auckland"],
  "PKT" => ["Asia/Karachi"],
  "KST" => ["Asia/Pyongyang","Asia/Seoul","ROK"],
  "BRST" => ["America/Sao_Paulo","Brazil/East"],
  "ANAT" => ["Asia/Anadyr"],
  "SAKT" => ["Asia/Sakhalin"],
  "IRST" => ["Asia/Tehran","Iran"],
  "AKDT" =>
      ["America/Anchorage","America/Juneau","America/Nome",
       "America/Sitka","America/Yakutat","US/Alaska"],
  "BTT" => ["Asia/Thimbu","Asia/Thimphu"],
  "GMT-14" => ["Etc/GMT-14"],
  "GMT-3" => ["Etc/GMT-3"],
  "GMT+12" => ["Etc/GMT+12"],
  "MIST" => ["Antarctica/Macquarie"],
  "AMST" => ["America/Campo_Grande","America/Cuiaba"],
  "PGT" => ["Pacific/Port_Moresby"],
  "HOVT" => ["Asia/Hovd"],
  "CET" =>
      ["Africa/Algiers","Africa/Ceuta","Africa/Tunis",
       "Arctic/Longyearbyen","Atlantic/Jan_Mayen","CET",
       "Europe/Amsterdam","Europe/Andorra","Europe/Belgrade",
       "Europe/Berlin","Europe/Bratislava","Europe/Brussels",
       "Europe/Budapest","Europe/Busingen","Europe/Copenhagen",
       "Europe/Gibraltar","Europe/Ljubljana","Europe/Luxembourg",
       "Europe/Madrid","Europe/Malta","Europe/Monaco",
       "Europe/Oslo","Europe/Paris","Europe/Podgorica",
       "Europe/Prague","Europe/Rome","Europe/San_Marino",
       "Europe/Sarajevo","Europe/Skopje","Europe/Stockholm",
       "Europe/Tirane","Europe/Vaduz","Europe/Vatican",
       "Europe/Vienna","Europe/Warsaw","Europe/Zagreb",
       "Europe/Zurich","Poland"],
  "GMT-4" => ["Etc/GMT-4"],
  "PHOT" => ["Pacific/Enderbury"],
  "GMT+10" => ["Etc/GMT+10"],
  "TVT" => ["Pacific/Funafuti"],
  "TAHT" => ["Pacific/Tahiti"],
  "GMT-5" => ["Etc/GMT-5"],
  "WITA" => ["Asia/Makassar","Asia/Ujung_Pandang"],
  "CHUT" => ["Pacific/Chuuk","Pacific/Truk","Pacific/Yap"],
  "CDT" =>
      ["America/Bahia_Banderas","America/Cancun",
       "America/Chicago","America/Havana","America/Indiana/Knox",
       "America/Indiana/Tell_City","America/Knox_IN",
       "America/Matamoros","America/Menominee","America/Merida",
       "America/Mexico_City","America/Monterrey",
       "America/North_Dakota/Beulah","America/North_Dakota/Center",
       "America/North_Dakota/New_Salem","America/Rainy_River",
       "America/Rankin_Inlet","America/Resolute",
       "America/Winnipeg","CST6CDT","Canada/Central","Cuba",
       "Mexico/General","US/Central","US/Indiana-Starke"],
  "GMT-12" => ["Etc/GMT-12"],
  "TFT" => ["Indian/Kerguelen"],
  "GMT+8" => ["Etc/GMT+8"],
  "KGT" => ["Asia/Bishkek"],
  "ECT" => ["America/Guayaquil"],
  "UZT" => ["Asia/Samarkand","Asia/Tashkent"],
  "EGST" => ["America/Scoresbysund"],
  "GYT" => ["America/Guyana"],
  "ACT" =>
      ["America/Eirunepe","America/Porto_Acre",
       "America/Rio_Branco","Brazil/Acre"],
  "CST" =>
      ["America/Bahia_Banderas","America/Belize","America/Cancun",
       "America/Chicago","America/Costa_Rica",
       "America/El_Salvador","America/Guatemala","America/Havana",
       "America/Indiana/Knox","America/Indiana/Tell_City",
       "America/Knox_IN","America/Managua","America/Matamoros",
       "America/Menominee","America/Merida","America/Mexico_City",
       "America/Monterrey","America/North_Dakota/Beulah",
       "America/North_Dakota/Center",
       "America/North_Dakota/New_Salem","America/Rainy_River",
       "America/Rankin_Inlet","America/Regina","America/Resolute",
       "America/Swift_Current","America/Tegucigalpa",
       "America/Winnipeg","Asia/Chongqing","Asia/Chungking",
       "Asia/Harbin","Asia/Kashgar","Asia/Macao","Asia/Macau",
       "Asia/Shanghai","Asia/Taipei","Asia/Urumqi",
       "Australia/Adelaide","Australia/Adelaide",
       "Australia/Broken_Hill","Australia/Broken_Hill",
       "Australia/Darwin","Australia/North","Australia/South",
       "Australia/South","Australia/Yancowinna",
       "Australia/Yancowinna","CST6CDT","Canada/Central",
       "Canada/East-Saskatchewan","Canada/Saskatchewan","Cuba",
       "Mexico/General","PRC","ROC","US/Central",
       "US/Indiana-Starke"],
  "NZST" =>
      ["Antarctica/McMurdo","Antarctica/South_Pole","NZ",
       "Pacific/Auckland"],
  "PYST" => ["America/Asuncion"],
  "GMT+7" => ["Etc/GMT+7"],
  "WGT" => ["America/Godthab"],
  "GALT" => ["Pacific/Galapagos"],
  "NCT" => ["Pacific/Noumea"],
  "CAT" =>
      ["Africa/Blantyre","Africa/Bujumbura","Africa/Gaborone",
       "Africa/Harare","Africa/Kigali","Africa/Lubumbashi",
       "Africa/Lusaka","Africa/Maputo"],
  "LHST" =>
      ["Australia/LHI","Australia/LHI","Australia/Lord_Howe",
       "Australia/Lord_Howe"],
  "FKST" => ["Atlantic/Stanley"],
  "GMT-13" => ["Etc/GMT-13"],
  "PMST" => ["America/Miquelon"],
  "CVT" => ["Atlantic/Cape_Verde"],
  "UYST" => ["America/Montevideo"],
  "HADT" => ["America/Adak","America/Atka","US/Aleutian"],
  "JST" => ["Asia/Tokyo","Japan"],
  "SRT" => ["America/Paramaribo"],
  "GMT" =>
      ["Africa/Abidjan","Africa/Accra","Africa/Bamako",
       "Africa/Banjul","Africa/Bissau","Africa/Conakry",
       "Africa/Dakar","Africa/Freetown","Africa/Lome",
       "Africa/Monrovia","Africa/Nouakchott","Africa/Ouagadougou",
       "Africa/Sao_Tome","Africa/Timbuktu","America/Danmarkshavn",
       "Atlantic/Reykjavik","Atlantic/St_Helena","Eire","Etc/GMT",
       "Etc/GMT+0","Etc/GMT-0","Etc/GMT0","Etc/Greenwich",
       "Europe/Belfast","Europe/Dublin","Europe/Guernsey",
       "Europe/Isle_of_Man","Europe/Jersey","Europe/London","GB",
       "GB-Eire","GMT","GMT+0","GMT-0","GMT0","Greenwich",
       "Iceland"],
  "DAVT" => ["Antarctica/Davis"],
  "IST" =>
      ["Asia/Calcutta","Asia/Colombo","Asia/Jerusalem",
       "Asia/Kolkata","Asia/Tel_Aviv","Eire","Europe/Dublin",
       "Israel"],
  "ICT" =>
      ["Asia/Bangkok","Asia/Ho_Chi_Minh","Asia/Phnom_Penh",
       "Asia/Saigon","Asia/Vientiane"],
  "HAST" => ["America/Adak","America/Atka","US/Aleutian"],
  "PETT" => ["Asia/Kamchatka"],
  "MST" =>
      ["America/Boise","America/Cambridge_Bay",
       "America/Chihuahua","America/Creston",
       "America/Dawson_Creek","America/Denver","America/Edmonton",
       "America/Hermosillo","America/Inuvik","America/Mazatlan",
       "America/Ojinaga","America/Phoenix","America/Shiprock",
       "America/Yellowknife","Canada/Mountain","MST","MST7MDT",
       "Mexico/BajaSur","Navajo","US/Arizona","US/Mountain"],
  "TOT" => ["Pacific/Tongatapu"],
  "CEST" =>
      ["Africa/Ceuta","Arctic/Longyearbyen","Atlantic/Jan_Mayen",
       "CET","Europe/Amsterdam","Europe/Andorra","Europe/Belgrade",
       "Europe/Berlin","Europe/Bratislava","Europe/Brussels",
       "Europe/Budapest","Europe/Busingen","Europe/Copenhagen",
       "Europe/Gibraltar","Europe/Ljubljana","Europe/Luxembourg",
       "Europe/Madrid","Europe/Malta","Europe/Monaco",
       "Europe/Oslo","Europe/Paris","Europe/Podgorica",
       "Europe/Prague","Europe/Rome","Europe/San_Marino",
       "Europe/Sarajevo","Europe/Skopje","Europe/Stockholm",
       "Europe/Tirane","Europe/Vaduz","Europe/Vatican",
       "Europe/Vienna","Europe/Warsaw","Europe/Zagreb",
       "Europe/Zurich","Poland"],
  "YEKT" => ["Asia/Yekaterinburg"],
  "BRT" =>
      ["America/Araguaina","America/Bahia","America/Belem",
       "America/Fortaleza","America/Maceio","America/Recife",
       "America/Santarem","America/Sao_Paulo","Brazil/East"],
  "TJT" => ["Asia/Dushanbe"],
  "MUT" => ["Indian/Mauritius"],
  "SAST" =>
      ["Africa/Johannesburg","Africa/Maseru","Africa/Mbabane"],
  "WST" =>
      ["Antarctica/Casey","Australia/Perth","Australia/West",
       "Pacific/Apia"],
  "ADT" =>
      ["America/Glace_Bay","America/Goose_Bay","America/Halifax",
       "America/Moncton","America/Thule","Atlantic/Bermuda",
       "Canada/Atlantic"],
  "MAGT" => ["Asia/Magadan"]}).
